parameters:
#    cokidoo_seo_breadcrumb.example.class: Cokidoo\SEOBreadcrumbBundle\Example

services:
#    cokidoo_seo_breadcrumb.example:
#        class: %cokidoo_seo_breadcrumb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
